--MAURÍCIO VIEIRA PEREIRA - RM553748
--LUIZ OTÁVIO LEITÃO SILVA - RM553542
--VITOR ONOFRE RAMOS - RM553241

drop table GS_USERS cascade constraints;
drop table GS_ADDRESSES cascade constraints;
drop table GS_COMPANIES cascade constraints;
drop table GS_PRODUCTS cascade constraints;
drop table GS_ORDERS cascade constraints;
drop table GS_ORDER_ITEMS cascade constraints;
drop table GS_NGOS cascade constraints;
drop table GS_DONATIONS cascade constraints;



CREATE TABLE GS_USERS (
    USER_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME VARCHAR2(255) NOT NULL,
    SOBRENOME VARCHAR2(255) NOT NULL,
    EMAIL VARCHAR2(255) NOT NULL UNIQUE,
    PASSWORD VARCHAR2(255) NOT NULL,
    USER_TYPE VARCHAR2(50) NOT NULL,
    PHONE VARCHAR2(20),
    BIRTHDATE DATE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CHECK (USER_TYPE IN ('buyer', 'admin_company', 'admin_ngo'))
);

CREATE TABLE GS_ADDRESSES (
    ADDRESS_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USER_ID NUMBER NOT NULL,
    ZIP_CODE VARCHAR2(20) NOT NULL,
    COUNTRY VARCHAR2(255) NOT NULL,
    STATE VARCHAR2(255) NOT NULL,
    CITY VARCHAR2(255) NOT NULL,
    NEIGHBORHOOD VARCHAR2(255) NOT NULL,
    STREET VARCHAR2(255) NOT NULL,
    "NUMBER" VARCHAR2(20) NOT NULL,
    COMPLEMENT VARCHAR2(255),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES GS_USERS(USER_ID) ON DELETE CASCADE
);

CREATE TABLE GS_COMPANIES (
    COMPANY_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME VARCHAR2(255) NOT NULL,
    CNPJ VARCHAR2(20) NOT NULL UNIQUE,
    PHONE VARCHAR2(20) NOT NULL,
    WEBSITE VARCHAR2(255) NOT NULL,
    ADMIN_ID NUMBER NOT NULL,
    VERIFICATION_STATUS VARCHAR2(50) DEFAULT 'unverified',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FOREIGN KEY (ADMIN_ID) REFERENCES GS_USERS(USER_ID) ON DELETE CASCADE
);

CREATE TABLE GS_PRODUCTS (
    PRODUCT_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME VARCHAR2(255) NOT NULL,
    DESCRIPTION VARCHAR2(1000),
    PRICE NUMBER(10, 2) NOT NULL,
    STOCK NUMBER NOT NULL,
    COMPANY_ID NUMBER NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FOREIGN KEY (COMPANY_ID) REFERENCES GS_COMPANIES(COMPANY_ID) ON DELETE CASCADE
);

CREATE TABLE GS_ORDERS (
    ORDER_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ORDER_NUMBER VARCHAR2(255) NOT NULL UNIQUE,
    BUYER_ID NUMBER NOT NULL,
    TOTAL_AMOUNT NUMBER(10, 2) DEFAULT 0,
    DONATION_AMOUNT NUMBER(10, 2) DEFAULT 0,
    MAINTENANCE_AMOUNT NUMBER(10, 2) DEFAULT 0,
    ORDER_STATUS VARCHAR2(50) DEFAULT 'pending',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FOREIGN KEY (BUYER_ID) REFERENCES GS_USERS(USER_ID) ON DELETE CASCADE,
    CHECK (ORDER_STATUS IN ('paid', 'pending', 'canceled'))
);

CREATE TABLE GS_ORDER_ITEMS (
    ORDER_ITEM_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ORDER_ID NUMBER NOT NULL,
    PRODUCT_ID NUMBER NOT NULL,
    QUANTITY NUMBER NOT NULL,
    PRICE NUMBER(10, 2) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FOREIGN KEY (ORDER_ID) REFERENCES GS_ORDERS(ORDER_ID) ON DELETE CASCADE,
    FOREIGN KEY (PRODUCT_ID) REFERENCES GS_PRODUCTS(PRODUCT_ID) ON DELETE CASCADE
);

CREATE TABLE GS_NGOS (
    NGO_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CONTACT_USER_ID NUMBER NOT NULL,
    NAME VARCHAR2(255) NOT NULL,
    MISSION VARCHAR2(1000),
    PHONE VARCHAR2(20),
    WEBSITE VARCHAR2(255),
    CONTACT_EMAIL VARCHAR2(255),
    TOTAL_DONATIONS NUMBER(10, 2) DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FOREIGN KEY (CONTACT_USER_ID) REFERENCES GS_USERS(USER_ID) ON DELETE CASCADE
);

CREATE TABLE GS_DONATIONS (
    DONATION_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ORDER_ID NUMBER NOT NULL,
    AMOUNT NUMBER(10, 2) NOT NULL,
    NGO_ID NUMBER NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FOREIGN KEY (ORDER_ID) REFERENCES GS_ORDERS(ORDER_ID) ON DELETE CASCADE,
    FOREIGN KEY (NGO_ID) REFERENCES GS_NGOS(NGO_ID) ON DELETE CASCADE
);

commit;